name: CI/CD for Quiz App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install prerequisites (unzip)
        run: |
          apt-get update -y
          apt-get install -y unzip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init Terraform
        working-directory: Iac-deployment
        run: terraform init

      - name: Validate Terraform
        working-directory: Iac-deployment
        run: terraform validate

      - name: Run Terraform apply
        working-directory: Iac-deployment
        run: terraform apply -auto-approve
